[global]
flavor = "github"

disable = [
  "MD013", # Line length
  "MD025", # Single h1
  "MD040", # Fenced code language
  "MD041", # First line h1
  "MD047", # File end newline
]

extend-enable = [
  "MD060" # Table formatting
]

exclude = [
  "node_modules",
  "build",
  "dist",
]
