return {
  "m4xshen/hardtime.nvim",
  lazy = false,
  dependencies = { "MunifTanjim/nui.nvim" },
  opts = {
    -- This overrides the default, so I copied the default and added myself.
    disabled_filetypes = {
      "aerial",
      "alpha",
      "Avante",
      "checkhealth",
      "dapui*",
      "db*",
      "Diffview*",
      "Dressing*",
      "fugitive",
      "help",
      "httpResult",
      "lazy",
      "lspinfo",
      "markdown",
      "mason",
      "minifiles",
      "Neogit*",
      "neo%-tree*",
      "neotest%-summary",
      "netrw",
      "noice",
      "notify",
      "NvimTree",
      "oil",
      "Outline",
      "prompt",
      "qf",
      "query",
      "TelescopePrompt",
      "Trouble",
      "trouble",
      "VoltWindow",
      "undotree",
    },
  },
}
